apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kj1yi23fy-go 
  janus-idp.io/tekton: kj1yi23fy-go
  backstage.io/kubernetes-id: kj1yi23fy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kj1yi23fy-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  